#include "include/iis/web_config.h"

#include <cstdio>
#include <stdexcept>

#include "include/iis/validators.h"

namespace fairyfly::iis {
namespace {

std::string xml_escape(const std::string& in) {
    std::string out;
    for (const char c : in) {
        switch (c) {
            case '&': out += "&amp;"; break;
            case '<': out += "&lt;"; break;
            case '>': out += "&gt;"; break;
            case '"': out += "&quot;"; break;
            case '\'': out += "&apos;"; break;
            default:
                if (static_cast<unsigned char>(c) < 0x20) throw std::invalid_argument("control character in web.config value");
                out += c;
        }
    }
    return out;
}

void set_var(std::string& out, const std::string& name, const std::string& value, const char* indent) {
    out += indent;
    out += "<set name=\"" + xml_escape(name) + "\" value=\"" + xml_escape(value) + "\" />\n";
}

} // namespace

const std::vector<std::string>& required_server_variables() {
    static const std::vector<std::string> vars = {
        "HTTP_X_FORWARDED_FOR", "HTTP_X_FORWARDED_PROTO", "HTTP_X_FORWARDED_HOST", "HTTP_X_FAIRYFLY_PROXY_SECRET",
        "HTTP_X_REAL_IP",       "HTTP_FORWARDED",         "HTTP_ACCEPT_ENCODING",
    };
    return vars;
}

std::string format_timespan(int seconds) {
    if (seconds < 1) seconds = 1;
    char buf[32];
    std::snprintf(buf, sizeof buf, "%02d:%02d:%02d", seconds / 3600, (seconds / 60) % 60, seconds % 60);
    return buf;
}

std::string generate_web_config(const WebConfigParams& p) {
    if (const auto e = upstream_error(p.upstream)) throw std::invalid_argument(*e);
    if (p.proxy_secret.empty()) throw std::invalid_argument("proxy secret is empty");
    if (!p.allow_any_ip && p.allow_ips.empty()) throw std::invalid_argument("allow_ips is empty and allow_any_ip is false");
    for (const auto& ip : p.allow_ips) {
        if (const auto e = cidr_error(ip)) throw std::invalid_argument("allow-ip '" + ip + "': " + *e);
    }
    if (p.proxy_timeout_seconds < 1 || p.max_content_bytes < 1 || p.hsts_max_age_seconds < 0)
        throw std::invalid_argument("numeric web.config parameter out of range");

    std::string x;
    x += "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
    x += "<!-- Generated by `fairyfly mcp iis setup`. Manual edits are reported as drift by `mcp iis status`. -->\n";
    x += "<configuration>\n";
    x += "  <system.webServer>\n";

    // URL Rewrite: hygiene rule, /mcp proxy rule, 404 for everything else.
    x += "    <rewrite>\n";
    x += "      <rules>\n";
    x += "        <clear />\n";
    x += "        <rule name=\"fairyfly-strip-spoofed-headers\" stopProcessing=\"false\">\n";
    x += "          <match url=\".*\" />\n";
    x += "          <serverVariables>\n";
    for (const char* v : {"HTTP_X_FORWARDED_FOR", "HTTP_X_FORWARDED_PROTO", "HTTP_X_FORWARDED_HOST",
                          "HTTP_X_FAIRYFLY_PROXY_SECRET", "HTTP_X_REAL_IP", "HTTP_FORWARDED"}) {
        set_var(x, v, "", "            ");
    }
    x += "          </serverVariables>\n";
    x += "          <action type=\"None\" />\n";
    x += "        </rule>\n";
    x += "        <rule name=\"fairyfly-mcp\" stopProcessing=\"true\">\n";
    x += "          <match url=\"^mcp/?$\" />\n";
    x += "          <serverVariables>\n";
    set_var(x, "HTTP_X_FORWARDED_FOR", "{REMOTE_ADDR}", "            ");
    set_var(x, "HTTP_X_FORWARDED_PROTO", "https", "            ");
    set_var(x, "HTTP_X_FORWARDED_HOST", "{HTTP_HOST}", "            ");
    set_var(x, "HTTP_X_FAIRYFLY_PROXY_SECRET", p.proxy_secret, "            ");
    set_var(x, "HTTP_ACCEPT_ENCODING", "", "            ");
    x += "          </serverVariables>\n";
    x += "          <action type=\"Rewrite\" url=\"" + xml_escape(p.upstream) + kMcpPath + "\" appendQueryString=\"true\" />\n";
    x += "        </rule>\n";
    x += "        <rule name=\"fairyfly-deny-everything-else\" stopProcessing=\"true\">\n";
    x += "          <match url=\".*\" />\n";
    x += "          <action type=\"CustomResponse\" statusCode=\"404\" statusReason=\"Not Found\" statusDescription=\"Not Found\" />\n";
    x += "        </rule>\n";
    x += "      </rules>\n";
    x += "    </rewrite>\n";

    // ARR: no response buffering (SSE), timeout above the MCP call timeout.
    x += "    <proxy enabled=\"true\" timeout=\"" + format_timespan(p.proxy_timeout_seconds) +
         "\" responseBufferLimit=\"0\" reverseRewriteHostInResponseHeaders=\"false\" />\n";

    x += "    <security>\n";
    x += "      <requestFiltering removeServerHeader=\"true\">\n";
    x += "        <requestLimits maxAllowedContentLength=\"" + std::to_string(p.max_content_bytes) + "\" />\n";
    x += "        <verbs allowUnlisted=\"false\">\n";
    x += "          <add verb=\"GET\" allowed=\"true\" />\n";
    x += "          <add verb=\"POST\" allowed=\"true\" />\n";
    x += "          <add verb=\"DELETE\" allowed=\"true\" />\n";
    x += "          <add verb=\"OPTIONS\" allowed=\"true\" />\n";
    x += "        </verbs>\n";
    x += "      </requestFiltering>\n";
    if (p.allow_any_ip) {
        x += "      <!-- WARNING: --allow-any-ip was used: no IIS IP restriction is active. -->\n";
    } else {
        x += "      <ipSecurity allowUnlisted=\"false\" enableReverseDns=\"false\">\n";
        for (const auto& ip : p.allow_ips) {
            if (const auto range = ipv4_range(ip)) {
                x += "        <add ipAddress=\"" + range->address + "\" subnetMask=\"" + range->mask + "\" allowed=\"true\" />\n";
            } else {
                x += "        <add ipAddress=\"" + xml_escape(ip) + "\" allowed=\"true\" />\n";
            }
        }
        x += "      </ipSecurity>\n";
    }
    x += "    </security>\n";

    x += "    <httpProtocol>\n";
    x += "      <customHeaders>\n";
    x += "        <remove name=\"X-Powered-By\" />\n";
    x += "        <add name=\"Strict-Transport-Security\" value=\"max-age=" + std::to_string(p.hsts_max_age_seconds) + "\" />\n";
    x += "      </customHeaders>\n";
    x += "    </httpProtocol>\n";
    x += "    <urlCompression doStaticCompression=\"false\" doDynamicCompression=\"false\" />\n";
    x += "    <directoryBrowse enabled=\"false\" />\n";
    x += "    <defaultDocument enabled=\"false\" />\n";
    x += "    <httpErrors existingResponse=\"PassThrough\" />\n";
    x += "  </system.webServer>\n";
    x += "</configuration>\n";
    return x;
}

std::string content_hash(const std::string& text) {
    unsigned long long h = 14695981039346656037ULL;
    for (const unsigned char c : text) {
        h ^= c;
        h *= 1099511628211ULL;
    }
    char buf[20];
    std::snprintf(buf, sizeof buf, "%016llx", h);
    return buf;
}

std::string mask_secret(std::string text, const std::string& secret) {
    if (secret.empty()) return text;
    size_t pos = 0;
    while ((pos = text.find(secret, pos)) != std::string::npos) {
        text.replace(pos, secret.size(), kSecretPlaceholder);
        pos += std::char_traits<char>::length(kSecretPlaceholder);
    }
    return text;
}

} // namespace fairyfly::iis
